machine:
  java:
    version: openjdk7
jobs:
  build:
    steps:
      - build_java
      - run: jar -cvf sample.war META-INF/ WEB-INF/ hello.jsp images/ index.html
  build:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker run -d --name db company/proprietary-db:1.2.3

      # build the application image
      - run: docker build -t company/app:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push company/app:$CIRCLE_BRANCH